project:
  type: website

website:
  title: "Carbon Dioxide and How It Is Effecting the World"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: models.qmd
        text: Models
      - href: sources.qmd
        text: Sources

format:
  html:
    theme: united
    css: styles.css
    toc: true



