project:
  type: website

website:
  title: "carbon-dioxide"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: sources.qmd
        text: Sources
      - href: models.qmd
        text: Models

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



