---
title: "Models"
editor: source
execute:
  echo: false
  message: false
  warning: false
---

```{r setup}
library(tidyverse)
library(janitor)
library(scales)
library(rstanarm)
library(gtsummary)
```

```{r read joined}
joined = read_csv("data/joined.csv")
joined_by_year = joined |>
  summarize("carbon_dioxide_emissions_sum" = sum(carbon_dioxide_emissions,
                                                 na.rm = TRUE),
            "land_temperature_avg" = mean(average_temperature,
                                         na.rm = TRUE),
            .by = year)
```

## How much carbon dioxide is going to be in the air in 2050?

### Model Definition

$$y_i = \beta_0  + \beta_1 x_{1,i} + \epsilon_i$$

with $y = carbon\_dioxide\_emissions$, $x_1 = year$, and $\epsilon_i \sim N(0, \sigma^2)$.

### Fitted Model

```{r model 1}
fit_obj <- stan_glm(formula = carbon_dioxide_emissions_sum ~ year,
                    data = joined_by_year,
                    refresh = 0,
                    seed = 9)
fit_obj
```

### Plot

```{r posterior epred 1}
newobs = tibble(year = 2050)
pe = posterior_epred(fit_obj,
                     newdata = newobs) |>
  as_tibble()
```

```{r plot 1}
pe |>
  ggplot(aes(x = `1`)) +
  geom_histogram(aes(y = after_stat(count/sum(count))), bins = 100) +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  theme_classic() +
  labs(title = "Posterior of Carbon Dioxide in 2050",
       subtitle = "around 53,000 (MtC02e) of carbon dioxide is going to be in the year 2050. ",
       x = "Carbon Dioxide Emissions (MtC02e)",
       y = "Percent")
```

## What is going to be the average land temperature in 2050?

### Model Definition

$$y_i = \beta_0  + \beta_1 x_{1,i} + \epsilon_i$$

with $y = average\_land\_temperature$, $x_1 = year$, and $\epsilon_i \sim N(0, \sigma^2)$.

### Fitted Model

```{r model 2}
fit_obj2 <- stan_glm(formula = land_temperature_avg ~ year,
                    data = joined_by_year,
                    refresh = 0,
                    seed = 42)
fit_obj2
```

### Plot

```{r posterior epred 2}
newobs2 = tibble(year = 2050)
pe2 = posterior_epred(fit_obj2,
                     newdata = newobs2) |>
  as_tibble()
```

```{r plot 2}
pe2 |>
  ggplot(aes(x = `1`)) +
  geom_histogram(aes(y = after_stat(count/sum(count))), bins = 100) +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  theme_classic() +
  labs(title = "Posterior of Average Land Temperature in 2050",
       subtitle = "The land temperature is going to be around 20.6 C in 2050.",
       x = "Temperature (C)",
       y = "Percent")
```
